[package]
name = "spkg"
version = "3.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37.0", features = ["rt", "macros", "rt-multi-thread"] }
futures-util = "0.3.30"

reqwest = { version = "0.12.4", features = ["stream"] }
stblib = "0.6.2"
sqlx = { version = "0.7.4", features = ["sqlite", "runtime-tokio-native-tls"]  }

serde = { version = "1.0.203", features = ["derive"] }
serde_yaml = "0.9.34"
strum = { version = "0.26.2", features = ["derive"] }

lazy_static = "1.4.0"
eyre = "0.6.12"


