[package]
name = "spkg"
version = "3.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.7.3", features = ["sqlite", "runtime-tokio-native-tls"]  }
tokio = { version = "1.20.0", features = ["rt", "macros", "rt-multi-thread"] }
futures-util = "0.3.30"
serde = "1.0.195"
serde_yaml = "0.9.30"
lazy_static = "1.4.0"
stblib = "0.5.13"
reqwest = { version = "0.11.23", features = ["stream"] }
rustyline = "14.0.0"
spinoff = "0.8.0"
anyhow = "1.0.79"

[profile.release]
opt-level = 'z'
strip = true
lto = true