[package]
name = "spkg_api"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.7.4", features = ["sqlite", "runtime-tokio-native-tls"]  }
lazy_static = "1.4.0"

thiserror = "1.0.61"
eyre = "0.6.12"