name: Bug
description: Report a bug
labels: [ bug ]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: |
        Describe the bug
    validations:
      required: true

  - type: textarea
    id: reproducing
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce this bug
      render: bash
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: The Error Text/Stacktrace
      
  - type: input
    id: version
    attributes:
      label: The version of spkg you used
    validations:
      required: true

  - type: dropdown
    id: operating-systems
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Android
    validations:
      required: true

  - type: dropdown
    id: operating-system-specific
    attributes:
      label: Specific Operating System
      options:
        - Debian
        - Ubuntu
        - serverOS
        - coreOS
        - Fedora
        - Alpine
        - openSUSE
        - other
    validations:
      required: true

- type: input
    id: operating-system-specific-version
    attributes:
      label: Operating System Version
    validations:
      required: true

  - type: input
    id: operating-system-specific-other
    attributes:
      label: Specific Operating System (only fill when selected "other")
    validations:
      required: false

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Before submitting a bug report
      options:
        - label: |
            This bug wasn't already reported (I have searched bug reports on GitHub).
          required: true
        - label: |
            This bug isn't fixed in the latest version of spkg (including git release)
          required: true
