name: New Package
description: Suggest a new package in the package database
labels: [ new package ]
body:
  - type: input
    id: description
    attributes:
      label: Package name
      description: The name of the package
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Repo URL
      description: The URL of the repository of the package
    validations:
      required: true
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Before submitting a suggestion
      options:
        - label: |
            This package is not already in the package database
          required: true
        - label: |
            This package was not already suggested
          required: true
        - label: |
            This package is safe, does not contain viruses, does not destroy the system, does not commit data collection and does not do evil things. 
          required: true
        - label: |
            I give permission to customize my setup script according to your needs. 
          required: true
